models.py
from django.db import models

# Create your models here.

class Nurse(models.Model):
    
    Nombre= models.CharField(max_length=200)
    Apellido= models.CharField(max_length=100)
    Profesion= models.CharField(max_length=100)
    fecha_ingreso= models.DateField()
    
class Turno(models.Model):
    Nombre = models.CharField(max_length=200)
    Apellido = models.CharField(max_length=100, default='')  
    fecha = models.DateField()
    descripcion = models.CharField(max_length=255)

class FrancoProgramado(models.Model):
    Nombre= models.CharField(max_length=200, default='ValorPorDefecto')
    Apellido= models.CharField(max_length=100, default='')  
    fecha = models.DateField()
    motivo = models.CharField(max_length=255)

class Licencia(models.Model):
    Nombre= models.CharField(max_length=200,default='your_default_value')
    Apellido = models.CharField(max_length=100, default='')  
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    motivo = models.CharField(max_length=255)

forms.py
from django import forms
from .models import *

class NurseForm(forms.Form):
    Nombre= forms.CharField(max_length=200)
    Apellido= forms.CharField(max_length=100)
    Profesion= forms.CharField(max_length=100)
    fecha_ingreso= forms.DateField()

class TurnoForm(forms.Form):
    Nombre= forms.CharField(max_length=200)
    Apellido= forms.CharField(max_length=100)
    fecha = forms.DateField()
    descripcion = forms.CharField(max_length=255)

class FrancoProgramadoForm(forms.Form):
    Nombre= forms.CharField(max_length=200)
    Apellido= forms.CharField(max_length=100)
    fecha = forms.DateField()
    motivo = forms.CharField(max_length=255)

class LicenciaForm(forms.Form):
    Nombre= forms.CharField(max_length=200)
    Apellido = forms.CharField(max_length=100)
    fecha_inicio = forms.DateField(input_formats=['%d/%m/%Y'])
    fecha_fin = forms.DateField(input_formats=['%d/%m/%Y'])
    motivo = forms.CharField(max_length=255)
    

views.py
from django.shortcuts import render
from .models import Nurse, Turno, FrancoProgramado, Licencia
from .forms import *

# Create your views here.


def inicio(request):
    
    return render(request, "inicio.html")


def index(request):
    if request.method == "POST":
        info_formulario = NurseForm(request.POST)
        
        if info_formulario.is_valid():
            info = info_formulario.cleaned_data
            nuevo_enfermero = Nurse(
                Nombre=info["Nombre"],
                Apellido=info["Apellido"],
                Profesion=info["Profesion"],
                fecha_ingreso=info["fecha_ingreso"]
            )
            nuevo_enfermero.save()
            return render(request, "Enfermeros.html")
    else:
        try:
            nuevo_formulario = NurseForm()
        except Exception as e:
            print(f"Error al crear el formulario: {e}")
            nuevo_formulario = None  
    
    return render(request, "Enfermeros.html", {"formu": nuevo_formulario if 'nuevo_formulario' in locals() else None})

def insertar_turno(request):
    if request.method == "POST":
        info_form = TurnoForm(request.POST)
        if info_form.is_valid():
            info = info_form.cleaned_data
            Nombre = info_form.cleaned_data['Nombre']
            Apellido = info_form.cleaned_data['Apellido']
            nuevo_turno = Turno(
                Nombre=Nombre,
                Apellido=Apellido,
                fecha=info["fecha"],
                descripcion=info["descripcion"]
            )
            nuevo_turno.save()
            
            return render(request, "turnos.html", {"x": nuevo_turno})
    else:
        try:
            nuevo_formulario = TurnoForm()
        except Exception as e:
            print(f"Error al crear el formulario: {e}")
            nuevo_formulario = None  
    
    return render(request, "turnos.html", {"x": nuevo_formulario if 'nuevo_formulario' in locals() else None})



def FrancoPedido(request):
    if request.method == 'POST':
        form = FrancoProgramadoForm(request.POST)
        if form.is_valid():
            Nombre = form.cleaned_data['Nombre']
            Apellido= form.cleaned_data['Apellido']
            fecha = form.cleaned_data['fecha']
            motivo = form.cleaned_data['motivo']
            nuevo_franco_programado = FrancoProgramado(
                Nombre =Nombre,
                Apellido=Apellido,
                fecha=fecha,
                motivo=motivo
            )
            nuevo_franco_programado.save()

            return render(request, 'FrancoPedido.html', {'form': form})
    else:
        form = FrancoProgramadoForm()

    return render(request, 'FrancoPedido.html', {'form': form})


def Lic(request):
    if request.method == "POST":
        form = LicenciaForm(request.POST)
        if form.is_valid():
            Nombre = form.cleaned_data['Nombre']
            Apellido= form.cleaned_data['Apellido']
            fecha_inicio = form.cleaned_data['fecha_inicio']
            fecha_fin = form.cleaned_data['fecha_fin']
            motivo = form.cleaned_data['motivo']

            nueva_licencia = Licencia(
                Nombre =Nombre,
                Apellido=Apellido,
                fecha_inicio=fecha_inicio,
                fecha_fin=fecha_fin,
                motivo=motivo
            )
            nueva_licencia.save()

            return render(request, "Licencias.html", {"form": form})
    else:
        form = LicenciaForm()
    return render(request, "Licencias.html", {"form": form})

def busqueda_enfermero(request):
    
    return render(request, "AppEnfermeria/buscar_enfermero.html")

def resultado_busqueda(request):
    
    if request.method=="GET":
        Nombre= request.GET["Nombre"]
        resultado_busqueda= Nurse.objects.filter(Nombre__icontains=Nombre)
    return render(request, "AppEnfermeria/buscar_enfermero.html",{"Nombre": resultado_busqueda})

templates/Enfermeros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enfermeria</title>
</head>
<body>
    <h1> Aca agregamos personal de enfermeria </h1>
    <form action= "" method="POST"> {% csrf_token %}
        {{formu.as_p}}

        <input type="submit" value="Guardar">
    </form>

</body>
</html>

templates/FrancoPedido.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Francos</title>
</head>
<body>
    <h1>Aca agregamos francos programados</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{formu.as_p}}
        
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

templates/Licencias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Licencias</title>
</head>
<body>
    <h1>Aca se muestran las licencias</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Guardar">
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var fechaInicioInput = document.querySelector('#id_fecha_inicio');
            var fechaFinInput = document.querySelector('#id_fecha_fin');

            // Establece el tipo de entrada y el patrón para las fechas
            fechaInicioInput.type = 'text';
            fechaFinInput.type = 'text';

            fechaInicioInput.pattern = '\\d{2}/\\d{2}/\\d{4}';
            fechaFinInput.pattern = '\\d{2}/\\d{2}/\\d{4}';
        });
    </script>
</body>
</html>

templates/buscar_enfermero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search de Enfermeros</title>
</head>
<body>
    <h1> Aca realizamos la busqueda de enfermeros</h1>
    <form action="/resultadoBusqueda/" method="GET">
        Ingresa el nombre del Enfermero a buscar: <input type ="text">
        <input type= "submit" value="Buscar">
    </form>

    {% for x in enfermeros %}

    <p> {{x.nombre}} <p>

        {% endfor %}

</body>
</html>

templates/inicio.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppEnfermeria/assets/favicon.ico' % }" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppEnfermeria/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="#!"> Enfermeros </a>
                <a class="navbar-brand" href="#!"> Francos Pedidos </a>
                <a class="navbar-brand" href="#!"> Licencias </a>
                <a class="navbar-brand" href="#!"> Turnos </a>
                <a class="navbar-brand" href="#!"> Busqueda </a>
                <a class="btn btn-primary" href="#signup">Sign Up</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5"> Bienvenidos!!</h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <!-- Email address input-->
                                <div class="row">
                                    <div class="col">
                                        <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
                                    </div>
                                    <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                                </div>
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        <p>To activate this form, sign up at</p>
                                        <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        
        </section>
        <!-- Image Showcases-->

        </section>
        
        </section>
        <!-- Call to Action-->
        <section class="call-to-action text-white text-center" id="signup">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <h2 class="mb-4">Ready to get started? Sign up now!</h2>
                        <!-- Signup form-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form class="form-subscribe" id="contactFormFooter" data-sb-form-api-token="API_TOKEN">
                            <!-- Email address input-->
                            <div class="row">
                                <div class="col">
                                    <input class="form-control form-control-lg" id="emailAddressBelow" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                                    <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:required">Email Address is required.</div>
                                    <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:email">Email Address Email is not valid.</div>
                                </div>
                                <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                            </div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    <p>To activate this form, sign up at</p>
                                    <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/turnos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turnos Programados</title>
</head>
<body>
    <h1> Aca agregamos los turnos de Enfermería </h1>
    <form action="" method="POST"> {% csrf_token %}
        {{x.as_p}}

        <input type="submit" value="Guardar">
    </form>

</body>
</html>